# Generated by Django 3.1 on 2020-09-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='image_url',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='inner_description',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='inner_details',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='inner_imgae_url',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='inner_shipping_handling',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='outer_image_url',
            field=models.URLField(max_length=1024),
        ),
    ]
