# Generated by Django 3.1 on 2020-09-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='description',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='image_url',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='published_data',
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='tag',
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='title',
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='inner_description',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='inner_details',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='inner_imgae_url',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='inner_shipping_handling',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='inner_tag',
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='outer_image_url',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='outer_tag',
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='product_type',
            field=models.TextField(max_length=32),
        ),
    ]
