# Generated by Django 3.1 on 2020-09-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='account_id',
            new_name='account',
        ),
    ]
