# Generated by Django 3.1 on 2020-09-09 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='quantity',
        ),
    ]
