# Generated by Django 3.1 on 2020-09-09 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0003_remove_shopproduct_category'),
        ('basket', '0002_auto_20200909_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.account'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='category_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categoryproduct'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='basket',
            name='shop_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.shopproduct'),
        ),
    ]
