# Generated by Django 3.1 on 2020-09-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_remove_basket_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='shop_product',
        ),
        migrations.AddField(
            model_name='basket',
            name='product',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
